experiment:
  description: finetune fkernel sensitive health
  output_location: /project/def-dsuth/dnamrata/projects/mmd-b-fair/results/eq/health/skernel/
  load: /project/def-dsuth/dnamrata/projects/mmd-b-fair/results/eq/health/lambda_1/*/best.pth

data:
  data_key: heritage
  args:
    train: /home/dnamrata/scratch/data/heritage-health/train_charlson.csv
    val: /home/dnamrata/scratch/data/heritage-health/val_charlson.csv
    batch_size: 64
    target: CharlsonIndex_avg
    target_val: [0, 1]
    sensitive: AgeAtFirstClaim
    sensitive_val: [0, 1]
    factors: 
      - AgeAtFirstClaim
    factor_values:
      - [0, 1]
    value_fractions:
      - [1, 1]
    train_path: /home/dnamrata/scratch/data/heritage-health/train_charlson.csv
  num_workers: 16

model:
  model_key: fkernel
  trainer_key: fkernel_dp
  finetune: true
  fX:
    AgeAtFirstClaim: 1
  kernel: gaussian
  modes:
    - train
    - val
  epochs: 100
  alpha: 0.05
  lamda_t: 1
  lamda_s: 0
  var_offset: 0.000001
  unbiased_variance: False
  n_permutations: 100
  
  network:
    fc:
      - Linear:
          in_features: 65
          out_features: 128
      - LeakyReLU:
          inplace: true
      - Linear:
          in_features: 128
          out_features: 64
      - LeakyReLU:
          inplace: true
      - Linear:
          in_features: 64
          out_features: 16
    
    kernel_fc:
      - Linear:
          in_features: 16
          out_features: 32
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 32
          out_features: 16

  optimizers:
    ft:
      Adam:
        lr: 0.0001
        weight_decay: 0
  
  scheduler: null