experiment:
  description: finetune fkernel sensitive adult
  output_location: /project/def-dsuth/dnamrata/projects/mmd-b-fair/results/dp/adult/skernel/
  load: null

data:
  data_key: adult
  args:
    train: null
    val: null
    test: null
    train_path: /home/dnamrata/scratch/data/adult/adult.data
    test_path: /home/dnamrata/scratch/data/adult/adult.test
    batch_size: 64
    sensitive: sex
    clr_ratio: null
    factors: 
      - sex
    factor_values:
      - [0, 1]
    value_fractions:
      - [1, 1]
  num_workers: 16

model:
  model_key: fkernel
  trainer_key: fkernel_dp
  finetune: true
  fX:
    sex: 1
  kernel: gaussian
  modes:
    - test
  epochs: 0
  alpha: 0.05
  lamda_t: 0
  lamda_s: 1
  var_offset: 0.000001
  unbiased_variance: False
  n_permutations: 100
  
  network:
    fc:
      - Linear:
          in_features: 114
          out_features: 256
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 256
          out_features: 128
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 128
          out_features: 64 
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 64
          out_features: 32   
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 32
          out_features: 16
    
    kernel_fc:
      - Linear:
          in_features: 16
          out_features: 32
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 32
          out_features: 16

  optimizers:
    ft:
      Adam:
        lr: 0.0001
        weight_decay: 0
  
  scheduler: null