experiment:
  description: adult classifier test
  output_location: /project/def-dsuth/dnamrata/projects/mmd-b-fair/results/cls/adult/
  load: null
  resume: false

data:
  data_key: adult-cls
  args:
    train: null
    val: null
    test: null
    train_path: /home/dnamrata/scratch/data/adult/adult.data
    test_path: /home/dnamrata/scratch/data/adult/adult.test
    batch_size: 64
    tar_attr: income
    priv_attr: sex
    clr_ratio: null
  num_workers: 16

model:
  model_key: classifier
  trainer_key: classifier
  modes:
    - test
  epochs: 0
  finetune: False
  scls: false

  network:
    fc:
      - Linear:
          in_features: 114
          out_features: 256
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 256
          out_features: 128
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 128
          out_features: 64 
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 64
          out_features: 32   
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 32
          out_features: 16  
    classifier:
      - Linear:
          in_features: 16
          out_features: 2  

  optimizers:
    cls:
      Adam:
        lr: 0.0001
        weight_decay: 0.0001
  
  scheduler: null
