experiment:
  description: health classifier test
  output_location: /project/def-dsuth/dnamrata/projects/mmd-b-fair/results/cls/health/
  load: null
  resume: false

data:
  data_key: heritage-cls
  args:
    test: /home/dnamrata/scratch/data/heritage-health/test_charlson.csv
    batch_size: 64
    target: CharlsonIndex_avg
    sensitive: AgeAtFirstClaim
    og_target: CharlsonIndex_avg
    train_path: /home/dnamrata/scratch/data/heritage-health/train_charlson.csv
  num_workers: 16

model:
  model_key: classifier
  trainer_key: classifier
  modes:
    - test
  epochs: 0
  finetune: false
  scls: false

  network:
    fc:
      - Linear:
          in_features: 65
          out_features: 128
      - LeakyReLU:
          inplace: true
      - Linear:
          in_features: 128
          out_features: 64
      - LeakyReLU:
          inplace: true
      - Linear:
          in_features: 64
          out_features: 16

    classifier:
      - Linear:
          in_features: 16
          out_features: 16
      - LeakyReLU:
          inplace: true
      - Linear:
          in_features: 16
          out_features: 2     

  optimizers:
    cls:
      Adam:
        lr: 0.0001
        weight_decay: 0.0001
  
  scheduler: null