experiment:
  description: sipm health T1
  output_location: /project/def-dsuth/dnamrata/projects/mmd-b-fair/results/sipm/health/t1
  load: /project/def-dsuth/dnamrata/projects/mmd-b-fair/results/sipm/health/lambda_1000/*/best.pth
  resume: false

data:
  data_key: heritage-cls
  args:
    train: /home/dnamrata/scratch/data/heritage-health/train_transfer.csv
    val: /home/dnamrata/scratch/data/heritage-health/val_transfer.csv
    batch_size: 64
    target: prim_ARTHSPIN
    sensitive: AgeAtFirstClaim
    og_target: CharlsonIndex_avg
    train_path: /home/dnamrata/scratch/data/heritage-health/train_transfer.csv
  num_workers: 16

model:
  model_key: sipm
  trainer_key: sipm
  modes:
    - train
    - val
  epochs: 100
  aud_steps: 2
  lmda: 1
  lmdaR: 0
  lmdaF: 0
  s_cls: False
  finetune: True

  network:
    encoder_fc:
      - Linear:
          in_features: 65
          out_features: 128
      - LeakyReLU:
          inplace: true
      - Linear:
          in_features: 128
          out_features: 64
      - LeakyReLU:
          inplace: true
      - Linear:
          in_features: 64
          out_features: 16

    head:
      - Linear:
          in_features: 16
          out_features: 16
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 16
          out_features: 1
        activation: Sigmoid

    decoder:
      - Identity:
          args: unused

    aud:
      - Linear:
          in_features: 16
          out_features: 16
      - LeakyReLU:
          inplace: True
      - Linear:
          in_features: 16
          out_features: 1
        activation: Sigmoid

  optimizers:
    opt:
      Adadelta:
        lr: 2
        weight_decay: 0.0
    fair_opt:
      Adam:
        lr: 0.0001
