experiment:
  description: cfair-og adult
  output_location: /project/def-dsuth/dnamrata/projects/mmd-b-fair/results/cfair_og/adult/
  load: null

data:
  data_key: adult-cls
  args:
    train: null
    val: null
    test: null
    train_path: /home/dnamrata/scratch/data/adult/adult.data
    test_path: /home/dnamrata/scratch/data/adult/adult.test
    batch_size: 512
    tar_attr: income
    priv_attr: sex
    clr_ratio: null
  num_workers: 16

model:
  data_key: adult-cls
  model_key: cfair
  trainer_key: cfair-laftr
  num_classes: 2
  s_cls: false
  mu: 100
  modes:
    - train
    - val
  epochs: 500
  finetune: false

  encoder_fc:
    - Linear:
        in_features: 114
        out_features: 60
    - ReLU:
        inplace: True

  classifier:
    - Linear:
        in_features: 60
        out_features: 2  

  discriminator:
    - Linear:
        in_features: 60
        out_features: 50
    - ReLU:
        inplace: true
    - Linear:
        in_features: 50
        out_features: 2   

  optimizers:
    opt:
      Adadelta:
        lr: 1.0
        weight_decay: 0.0
  
  scheduler: null
